image: node:latest

before_script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl

stages:
    - "test"
    - "build"
    - "deploy"
    - "docker-build"

TestApp:
    stage: "test"
    script: 
            - yarn
            - yarn test

buildReact:
    stage: "build"
    script:
        - yarn
        - yarn build


docker-build:
    stage: "docker-build" 
    image: docker:19.03.12
    services:
        - docker:19.03.12-dind
    before_script:
        - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    script:
        - docker build --pull -t $CI_REGISTRY_IMAGE .
        - docker push $CI_REGISTRY_IMAGE

deploy:
  stage: deploy
  image: kroniak/ssh-client
  before_script:
    - echo "deploying app"
  script:
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > key.pem
    - chmod 400 key.pem
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP -p 12568 "docker pull registry.gitlab.com/6206021610111/gitlab_test-master"
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP -p 12568 "docker stop webserver || true && docker rm webserver || true"
    - ssh -o StrictHostKeyChecking=no -i key.pem root@$PROD_SERVER_IP -p 12568 "docker run -p 9999:80 -d --name webserver registry.gitlab.com/6206021610111/gitlab_test-master"
